http:
  middlewares:
    middlewares-basic-auth:
      basicAuth:
        realm: Traefik2 Basic Auth
        usersFile: /shared/.htpasswd
    middlewares-rate-limit:
        rateLimit:
          average: 100
          burst: 50
