
global:
  resolve_timeout: 5m

route:
  receiver: 'slack'
  repeat_interval: 15m
  group_interval: 5m
  group_wait: 1m
  routes:
    - receiver: 'logstash'
      continue: true

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        api_url: 'https://hooks.slack.com/services/<YOUR_KEY>'
        username: 'Prometheus - Alerter'
        channel: '#<CHANNEL_NAME>'
        text: '{{ .CommonAnnotations.summary }} ---> {{ .CommonAnnotations.description }}'

  - name: 'logstash'
    webhook_configs:
      # Whether or not to notify about resolved alerts.
      - send_resolved: true
        # The endpoint to send HTTP POST requests to.
        url: "http://logstash:8080/"
  